//
//  WorkoutsTableViewController.swift
//  Final App Project
//
//  Created by Liana Hill on 4/22/20.
//  Copyright © 2020 Liana Hill. All rights reserved.
//

import UIKit

class WorkoutsTableViewController: UITableViewController {

//The line of code below creates the base for all the workout information: the target area is the string, the name of the exercise, description and image are within the ExerciseList, the
    
//The equation goes Target Area, within ExerciseList is a list of exercises, within exercises the name of the exercise and Exercise, within Exercise is the description and image for each exercise

    var workouts = [String: ExerciseList]()
    
    override func viewDidLoad() {
        super.viewDidLoad()
        workouts = [
            "Biceps": ExerciseList(exercises:
                ["Bicep Curls": Exercise(description: "Step 1: Grab a pair of weights. Step 2: Stand tall with your feet about shoulder-width apart and knees slightly bent. Step 3: Hold a dumbbell in each hand with an underhand grip.Start with your arms fully extended by your sides. Keeping your elbows in line with your torso, curl the weights up to your shoulders.Step 4: Squeeze your biceps at the top of the curl. Using a controlled motion, straighten your arms back to a fully extended position.Step 5: Do 10 reps and 2-3 sets.", image: UIImage(named: "Bicep Curls")!),
                 "Feet Elevated Push-Ups": Exercise(description: "Step 1: Place your toes on a sturdy, elevated surface - like a bench, box, or step - and position yourself in a plank position with your hands shoulder-width-apart. Step 2: Keep your hands flat and your shoulders above your wrists. Remember to keep your core and glutes engaged. And your body should be a straight line from head to toe. Step 3: Bend your elbows and lower your chest to the floor. Step 4: Once you get as low as you can, push through the palms of your hands to straighten your arms. Step 5: Do 10 reps of 3 sets.", image: UIImage(named: "Feet Elevated Push Ups")!),
                 "Hammer Curls": Exercise(description: "Step 1: Grab a pair of weights. Step 2: Hold the weights down by your sides, with your palms facing inward and thumbs facing up. Step 3: Start with your elbows pulled into your sides and curl the weights up to your shoulders.Step 4: Finish the movement by extending your arms down slowly and with control. Step 5: Do 10 reps of 2-3 sets.", image: UIImage(named: "Hammer Curls")!),
                 "Isolated Single Arm Curls": Exercise(description: "Step 1: Grab a pair of weights. Step 2: Start with your arms extended, making a T-shape with your body, and with your weights in hand. Step 3: Hold the weights with an undergrip so your palms are facing up. Step 4: Curl one arm to about 90 degrees before returning the arm back down to be parallel with the ground. The other arm should stay extended parallel to the ground while the other curls. Step 5: Repeat the same steps with your other arm, alternating every time. Step 6; Do 10 reps of 2-3 sets on each arm.", image: UIImage(named: "Isolated Single Arm Curl")!),
                 "Bent Over Row": Exercise(description: "Step 1: Grab a pair of weights. Step 2: Stand with your feet hip-width apart, holding a weight in each hand with your arms at your sides. Step 3: With your core engaged, hinge forward at the hips, push your butt back, and bend your knees slightly, so that your back is no lower than parallel to the floor. (Depending on your hamstring flexibility, you may not be able to bend so far over.) Gaze at the ground a few inches in front of your feet to keep your neck in a comfortable position. Step 4: Do a row by pulling the weights up toward your chest, keeping your elbows hugged close to your body, and squeezing your shoulder blades for two seconds at the top of the movement. Your elbows should go past your back as you bring the weight toward your chest. Step 5: Slowly lower the weights by extending your arms toward the floor. This is 1 rep. Step 6: Do 10-12 reps of 2-3 sets.", image: UIImage(named: "Bent Over Row")!),
                 "Upright Row": Exercise(description: "Step 1: Grab a pair of weights. Step 2: Stand with your feet hip-width apart, holding a weight in each hand with your arms in front of your body, palms facing you. Step 3: With your back straight, core engaged, and chest lifted, slowly lift your hands to shoulder height. Your elbows should extend out to the sides. Step 4: Squeeze your shoulder blades at the top and hold for a second. Step 5: Slowly lower your hands back to starting position. This is 1 rep.Step 6: Do 10-12 reps for 2-3 sets.", image: UIImage(named: "Upright Row")!),
                 "Zottoman Curls": Exercise(description: "Step 1: Grab a pair of weights. Step 2: With your dumbbells hanging by your side, turn your arms so your palms face forward. Step 3: Without moving your upper arms, bend your elbows and curl the dumbbells towards your shoulder. Step 4: Pause, then rotate the dumbbells so your palms face forward before slowly returning back to your starting position. This is 1 rep. Step 5: Do 5-10 reps of 2-3 sets.", image: UIImage(named: "Zottoman Curls")!),
                 "Chin-Ups": Exercise(description: "This exercise requires a pull-up bar. Step 1: Place your hands about shoulder-width-apart on your pull-up bar. Make sure your palms are facing away from your body. Step 2: Start in a dead hang, and pull yourself up so that your chain reaches over the bar. Step 3: With control, lower yourself back down into a dead hang. That’s one rep. Step 4: Try for 5-10 reps for 2-3 sets. If that is too hard, try for 2-3 reps instead. Bonus: This is one variation of pull-ups. You could also widen your grip on your pull-up bar so your hands are wider than your shoulder-width. You can also adjust your grip so your palms face you, or rotate your grip.", image: UIImage(named: "Chin Ups")!)
            ]),
            "Triceps": ExerciseList(exercises:
                ["Diamond Push-Ups": Exercise(description: "This exercise does not require weights. Step 1: Start in a push-up position with your thumbs and index fingers of each hand touching to make a diamond shape. Step 2: While keeping your elbows as close to your side as possible, lower yourself down until your chest touches the back of your hands. Step 3: Keep everything tight throughout the movement. Step 4: Push back up to the starting position and repeat. Step 5: Do 10 reps and 2-3 sets. Tip: If this exercise is too hard, there are easier variations. Some include the Diamond Push-Up Against Wall, the Hands-Elevated Diamond Push-Up, and the Regular Push-Up on Floor.", image: UIImage(named: "Diamond Push Up")!),
                 "Bodyweight Tricep Dips": Exercise(description: "This exercise does not require weights. Step 1: Find a secure, chair, table, or bench, and place your hands shoulder-width-apart behind you with your fingers facing towards your body. Step 2: Bend your knees slightly.  Step 3: Straighten your arms without locking them, and then slowly bend your elbows and lower your body toward the floor, until your elbow is at about a 90-degree angle. Try not to push away from the bench. Keep your butt close to the bench. Step 4: Once your butt almost touches the ground, straighten your arms to push down on the bench. That’s 1 rep. Step 5: Do about 10-15 reps and 2-3 sets. Tip: Keep your heels on the floor and your elbows pointing directly behind your body (not flared out to the side).", image: UIImage(named: "Bodyweight Tricep Dips")!),
                 "Overhead Tricep Extensions": Exercise(description: "Step 1: Grab a pair of weights, but you’ll only need one for this exercise. Step 2: Hold one weight in both hands, extending it up overhead. You could do this sitting down on a bench, chair, or block, or you could also do this exercise standing up. Step 3: Keep your biceps close to your ears and elbows pointing forward as you lower the weight behind your head until the elbows are at about 90-degree angles. Step 4: Straighten the arms, contracting the triceps and repeat for 1-3 sets of 10 reps. Tip: Keep the abs engaged throughout the exercise and avoid arching the back.", image: UIImage(named: "Overhead Tricep Extensions")!),
                 "Push-Ups": Exercise(description: "This exercise does not require weights. Step 1: Start in a high plank with your palms flat, hands shoulder-width apart, shoulders stacked directly above your wrists, legs extended behind you, and your core and glutes engaged. Step 2: Bend your elbows and lower your chest to the floor. Drop to your knees if needed. Step 3: Push through the palms of your hands to straighten your arms. That's 1 rep.Step 4: Try for 5-10 reps for three sets.", image: UIImage(named: "Push Ups")!),
                 "Lateral Plank Walk": Exercise(description: "This exercise does not require weights. Step 1: Start in a high plank with your palms flat, hands shoulder-width apart, shoulders directly above your wrists, legs extended behind you, and your core and glutes engaged. Step 2: Step right, leading with your right hand and right foot, maintaining a plank as you move. That’s 1 rep. Step 3: Continue moving to the right for 10 steps. Step 4: Do your reps in one direction, and then repeat in the opposite direction. Step 5: Do 2-3 sets on each side.", image: UIImage(named: "Lateral Plank Walk")!),
                 "Burpee with Push Up": Exercise(description: "This exercise does not need weights. Step 1: Stand with your feet shoulder-width apart and arms by your sides. Step 2: Squat and reach forward to place your hands on the floor, shoulder-width apart. Step 3: Kick your legs straight out behind you into a high plank with your hands stacked underneath your shoulders. Step 4: Bend your elbows to lower your chest to the floor, then straighten them to do a push-up. Step 5: Jump your feet toward your hands so your lower body is in a squat. Jump straight up into the air, reaching your arms overhead. That's 1 rep. Step 6: Do 5-10 reps of 2-3 sets. Bonus: This exercise also works your glutes, core, and legs.", image: UIImage(named: "Burpee with Push Up")!),
                 "Dumbbell Floor Press": Exercise(description: "Step 1: Grab a pair of weights. Step 2: Lie on your back with your knees bent and feet placed flat on the ground. Step 3: Hold a dumbbell in each hand, and extend your arms upward over your chest, palms facing toward each other. Step 4: Slowly bend your arms and lower them to your sides until your triceps touch the ground. Your elbows should form a 45 degree angle with your body. Step 5: Slowly reverse the movement and return to start. That's one rep. Step 6: Complete 8 to 10 reps of 2-3 sets.", image: UIImage(named: "Dumbbell Floor Press")!),
                 "Single-Arm Tricep Kickbacks": Exercise(description: "Step 1: Grab a pair of weights. Step 2: Stand with your knees bent and lean forward slightly, with a dumbbell in each hand. Step 3: Bend both elbows to bring the dumbbells to your sides. Step 4: Press one dumbbell back, and as you straighten your arm, squeeze your triceps. Return to start. Step 5: Repeat on the other side. That's one rep.Step 6: Complete 8-10 reps of 2-3 sets.", image: UIImage(named: "Single Arm Tricep Kickbacks")!)
            ]),
            "Abs": ExerciseList(exercises:
                ["Plank": Exercise(description: "Step 1: Lying face down on the ground, prop yourself up in a forearm plank position. Step 2: Make sure your elbows are directly underneath your shoulders, and that your hands are balled into fists. Step 3: Keep your back and butt flat and level. Step 3: Try holding for 30 seconds per set. Try for 2-3 sets. Tip: To make it harder, push yourself to hold the plank for longer. If this is too hard, try going up into a push up position and hold your plank there.", image: UIImage(named: "Plank")!),
                 "Lemon Squeezes": Exercise(description: "Step 1: Lie flat on the ground with your hands above your head. Step 2: Lift your upper body off the ground. At the same time, bend your legs and use your core to lift them towards your chest. Bring your hands from above your head to be parallel to each other on either side of your body. Step 3: Extend yourself back towards the ground, bringing your arms back over your head and straightening your legs as they lower to the ground. That’s 1 rep. Step 4: Try 5-10 reps of 2-3 sets. If this is too hard, lower your number of reps. Tip: To make it more difficult, don’t let your legs or arms touch the ground as you go through your reps. You could also keep your arms by your side instead of going over your head. Bonus: Another variable is V-Ups, where instead of bending your legs, keep them squeezed tightly so they are straight. Then, lift your legs and upper body so your face almost touches your legs and your hands touch your toes to make a “V” shape. There is another variable of the V-Up. Instead of bringing both arms and legs up at the same time, alternate with one leg with the opposite arm (If you bring your right leg up, lift your left arm, and vice versa).", image: UIImage(named: "Lemon Squeezes")!),
                 "Bird Dog": Exercise(description: "Step 1: Start on your hands and knees. Make sure your shoulders are over your hands, your hips over your knees, and that your head is in a neutral position with your face towards the ground. Step 2: Extend your right arm and left leg simultaneously. Keep your foot flexed as you kick back and your palm should face the ground. Step 3: Pause for up to 3 seconds when your arm and leg are at the same height as your torso. Step 4: Bend your arm and leg and bring it back towards your body in a crunch. Step 5: Gently tap your elbow to your knee underneath your body. That’s 1 rep. Step 6: Continue on this side for 10-15 reps. Step 7: Repeat with your left arm and right leg for the same amount of reps. Step 8: Do 2-3 sets on each side.", image: UIImage(named: "Bird Dog")!),
                "Plank Tap": Exercise(description: "This exercise does not need weights. Step 1: Start in a high plank with your palms flat, hands shoulder-width apart, shoulders stacked directly above your wrists, legs extended behind you, and your core and glutes engaged. Step 2: Tap your right hand to your left shoulder while engaging your core and glutes to keep your hips as still as possible. Step 3: Do the same thing with your left hand to right shoulder. Continue, alternating sides. Step 4: Do three sets of 10 reps.", image: UIImage(named: "Plank Tap")!),
                "Plank Up-Down": Exercise(description: "This exercise does not require weights. Step 1: Start in a high plank with your palms flat, hands shoulder-width apart, shoulders stacked directly above your wrists, legs extended behind you, and your core and glutes engaged. Step 2: Place your feet hip-width apart. Step 3: Lower your left arm so that your forearm is on the floor. Then, do the same with your right so that you're in a forearm plank. Step 4: Reverse to return to a high plank. That’s one rep. Step 5: Do ten reps for three sets. Tip: As you move, keep your hips as still as possible. To make this easier, try widening your legs a little more.", image: UIImage(named: "Plank Up Down")!),
                "Downward Dog to Push-Up": Exercise(description: "This exercise does not need weights. Step 1: Start in a downward dog position. To get into a downward dog, start from an all-fours position with wrists under your shoulders and knees under your hips. Engage your core, lift your knees, and straighten both legs as your head drops naturally between your biceps and you come into an inverted V-shape. In downward dog, your arms and back should be straight and your hips piked up to the ceiling. Your heels do not need to touch the floor, but you should feel a nice stretch in the back of your legs. Step 2: From this position, lift your right hand and reach back to tap your left toes. Allow your torso to naturally rotate open so you can tap your toes. If you can't reach your toes, tap your shin or knee. Step 3: Return to downward dog and roll forward into a high plank or modified plank (by gently lowering your knees to the floor). Step 4: From your high plank or modified plank, do a push-up by bending both arms at the elbows and lowering your chest toward the floor in a smooth movement. Step 5: Push back up to return to your plank, then pike your hips to return to your downward dog. Now lift your left hand and tap your right toes. Step 6: After you've completed the toe tap, roll forward into a plank and do another push-up. Step 7: Continue your downward dog, to toe tap, to push-up progression for 5-10 reps for three sets. Bonus: This exercise also strengthens your triceps.", image: UIImage(named: "Downward Dog to Push Up")!),
                "Body Saw": Exercise(description: "This exercise does not require weights. Step 1: Start in a forearm plank with your forearms on the floor, elbows directly underneath your shoulders, hands facing forward so that your arms are parallel, and legs extended behind you. Step 2: Tuck your tailbone and engage your core, butt, and quads. Step 3: Rock forward on your forearms so your shoulders come in front of your elbows, and you come to the very tips of your toes. Step 4: Focus on moving as far forward as you can without piking your hips or losing your core engagement. Step 5: Now push in the other direction, rocking as far back as possible straightening your forearms slightly, and rolling onto the balls of your feet. Again, focus on maintaining core engagement and not piking your hips. Step 6: Continue to rock forward and back for 10 reps for three sets. Bonus: This exercise also strengthens your glutes.", image: UIImage(named: "Body Saw")!),
                "Inchworm": Exercise(description: "This exercise does not require weights. Step 1: Stand tall with your feet hip-width apart and arms at your sides. Step 2: Bend at your waist and place your hands on the floor. Step 3: Walk your hands forward to come into a high plank with your hands flat, wrists stacked under your shoulders, and your core, quads, and butt engaged. Pause for a second. Step 4: Walk your hands back to your feet and stand to return to start. That's 1 rep. Step 5: Repeat for 5-10 reps for 2-3 sets. Bonus: To make this harder, add a push-up when you are in the high plank position.", image: UIImage(named: "Inchworm")!)
            ]),
            "Obliques": ExerciseList(exercises:
                ["Side Plank": Exercise(description: "This exercise does not need weights. Step 1: Lie on your right side with your right hand directly underneath your right shoulder. Step 2: Extend your legs and stack your left foot on top of your right, and then squeeze your abs and glutes to lift your hips off the floor. Step 3: Extend your left hand straight up toward the ceiling. Step 4: Hold here for 30 seconds to a minute. Step 5: Switch to the left side and repeat the same process but with the left side. Step 6: Repeat holding for thirty seconds to a minute on each side twice.", image: UIImage(named: "Side Plank")!),
                 "Side Plank Dips": Exercise(description: "This exercise does not require weights. Step 1: Start in a side plank. Step 2: Drop your hips toward the floor and raise back to starting position or a little higher if you can. That’s 1 rep. Step 3: Try for 5-15 reps for 2-3 sets on each side. ", image: UIImage(named: "Side Plank Dips")!),
                 "Sit-Up Twists": Exercise(description: "This exercise does not require weights. Step 1: Lie on your back with your knees bent and feet flat to the floor. Step 2: Place your hands behind your head, engage your core and do a full sit-up. At the top of the sit-up, bring your right elbow to your left knee and twist your body toward that side. Step 3: Lower back down to start. That’s 1 rep. Step 5: Repeat this movement alternating sides each time. Step 6: Try for 5-15 reps for 2-3 sets.", image: UIImage(named: "Sit Up Twists")!),
                 "Standing Side Crunch": Exercise(description: "This exercise does not require weights. Step 1: Stand with your feet shoulder-width apart. Place your right hand close to your right ear. Step 2: Raise your right knee on the side of your body while bringing your right elbow down to meet it. Step 3: Raise your arm back up into the air as you straighten your leg and lower your foot back down to the ground. That’s 1 rep. Step 4: Do 10-15 reps on each side for 2-3 sets.", image: UIImage(named: "Standing Side Crunch")!),
                 "Russian Twists": Exercise(description: "Step 1: Sit up with your legs out in front of you, knees bent and your heels on the floor, your back at a 45-degree angle to the floor. Step 2: Hold a medicine ball or dumbbell (try 8 to 10 pounds) with both hands by your stomach. Step 3: Keep your back straight and the medicine ball in close to your torso as you twist to the right. That’s 1 rep. Step 4: Twist to the left side, and continue alternating sides. Step 5: Try for 10-15 reps for 2-3 sets. Bonus: To make this exercise harder, add a medicine ball. ", image: UIImage(named: "Russian Twists")!),
                 "Spidermans": Exercise(description: "This exercise does not require weights. Step 1: Start in a high plank, arms extended and your hands under your shoulders, with your core engaged. Step 2: Bring your left knee to your left elbow. Use your upper body to turn toward your knee to perform what looks like a side crunch. That’s 1 rep. Step 3: Continue the movement, alternating sides. Step 4: Do 10 reps on each side for 2-3 sets.", image: UIImage(named: "Spidermans")!),
                 "Side Bends": Exercise(description: "This exercise requires a dumbbell. Step 1: Stand with feet shoulder-width apart, holding a medium-to-heavy dumbbell in your right hand. Step 2: Engage your core and bend at your waist to the right toward the floor. Let the weight guide you down slowly. Step 3: Pulling from your core, bring your body back to the start position. That’s 1 rep. Step 4: Try for 5-10 reps for 2-3 sets on each side.", image: UIImage(named: "Side Bends")!),
                "Forward Lunge with Rotation": Exercise(description: "This exercise requires a medicine ball. Step 1: Stand with your feet hip-width apart. Hold a medicine ball in both hands with arms extended out in front of your chest. Step 2: Lunge forward with your left leg. As you bend your knees, rotate your torso to the left, making sure to keep your arms straight. Step 3: Rotate back to center, and push off your front heel to return to start. That’s 1 rep. Step 4: Continue this movement alternating legs. Step 5: Try for 5-10 reps for 2-3 sets on each side.", image: UIImage(named: "Forward Lunge with Rotation")!)
            ]),
            "Glutes": ExerciseList(exercises:
                ["Plank Jack": Exercise(description: "This exercise does not need weights. Step 1: Start in a high plank with your palms flat, hands shoulder-width apart, shoulders stacked directly above your wrists, legs extended behind you, and your core and glutes engaged. Step 2: Jump your feet out and in (like jumping jacks). Try not to let your butt and hips bounce as you jump. Step 3: Continue for thirty seconds to a minute. Step 4: Once the time is up, take a rest for two minutes before doing another set. Step 5: Try aiming for 3-4 sets. Bonus: This exercise also strengthens your core and triceps.", image: UIImage(named: "Plank Jack")!),
                 "Burpees": Exercise(description: "Step 1: Stand with your feet shoulder-width apart and arms by your sides. Step 2: Squat and reach forward to place your hands on the floor, shoulder-width apart. Step 3: Kick your legs straight out behind you into a high plank with your hands stacked underneath your shoulders. Step 4: Jump your feet toward your hands so your lower body is in a squat. Jump straight up into the air, reaching your arms overhead. That's 1 rep. Step 6: Do 5-10 reps of 2-3 sets.", image: UIImage(named: "Burpees")!),
                 "Squats": Exercise(description: "Step 1: Place your feet shoulder-width apart. Keep your feet, shoulders, and hips facing forward. Step 2: Bend your knees and extend your buttocks backward as if you are going to sit back into a chair. Make sure that you keep your knees behind your toes and your weight in your heels. Step 3: Push through your heels and rise back up to your standing position. That’s 1 rep. Step 4: Do 10-15 reps of 2-3 sets.Bonus: You can also add weights via exercise balls or dumbbells to make this exercise harder. You can also add a jump after your squat for Jump-Squats.", image: UIImage(named: "Squats")!),
                 "Lunges": Exercise(description: "Step 1: Start in a standing position with your hands on your hips, feet hip-width apart. Step 2: Take a big step forward with your right leg. Start to shift your weight forward so your heel hits the floor first. Step 3: Lower your body until the right thigh is parallel to the floor and the right shin is vertical.Make sure your knee does not go past your right toe. If you can, lightly tap your left knee to the floor while keeping weight in the right heel. Step 4: Press into your right heel to drive back up to starting position. That’s 1 rep. Step 5: Try for 10 reps for 2-3 sets on each side. Bonus: You can make this exercise harder by adding hand weights. You can also do Lateral Lunges and Curtsy Lunges as other variations.", image: UIImage(named: "Lunges")!),
                 "Glute Bridges": Exercise(description: "This exercise does not require any equipment. Step 1: Lie face up on the floor, with your knees bent and feet flat on the ground. Keep your arms at your side with your palms down. Step 2: Lift your hips off the ground until your knees, hips and shoulders form a straight line. Squeeze those glutes hard and keep your abs drawn in so you don’t overextend your back during the exercise. Step 3: Hold your bridged position for a couple of seconds before easing back down. That’s 1 rep. Step 4: Try for 10 reps for 2 sets.", image: UIImage(named: "Glute Bridges")!),
                 "Plank Leg Lifts": Exercise(description: "This exercise requires no equipment. Step 1: Start in a low plank position with your elbows bent, forearms on the ground, and body in a straight line. Keep your shoulders on top of your elbows and your feet hip-width-apart. Step 2: Lift your leg about 45 degrees and hold for 3 seconds before lowering your leg back down to the floor. That’s 1 rep. Step 3: Try for 10 reps for 1-2 sets on each side. Bonus: There are many variations to this exercise, one being Donkey Kicks, where your leg is bent instead of straight. This exercise also works your glutes, hamstrings, and quads.", image: UIImage(named: "Plank Leg Lifts")!),
                 "Clamshell": Exercise(description: "This exercise does not require any equipment. Step 1: Lie on your right side with your feet and hips stacked, your knees bent 90 degrees, and your head resting on your right arm. Draw your knees in toward your body until your feet are in line with your butt. Place your left hand on your left hip to ensure it doesn’t tilt backward. This is your starting position. Step 2: Keeping your abs engaged and your feet together, raise your left knee as far as you can without rotating your hip or lifting your right knee off the floor. Step 3: Hold for 1 second, squeezing your glutes at the top of the move, before slowly lowering your left knee to the starting position. That’s 1 rep. Step 4: Try for 10 reps for 1-2 sets on each side.", image: UIImage(named: "Clamshell")!),
                 "Candlestick Jump": Exercise(description: "Step 1: Start in a standing position. Step 2: Start to squat down towards the floor until you are completely sitting on your bottom. Step 3: Once you have reached the floor, roll onto your back. Step 4: Continute rolling backwards so that your butt no longer touches the floor and you are resting on your upper back. In this position, your legs and feet should be pointing towards the ceiling. Step 5: Gently bring your legs down as you start to sit back up. Step 5: You should now be sitting completely up with your feet resting flat on the ground and your legs bent. Step 6: Use your legs and core to stand up. Step 7: Once you are standing up, perform a jump. That's 1 rep. Step 8: Try for 5-10 for 2-3 sets. ", image: UIImage(named: "Candlestick Jump")!)
            ]),
            "Quads": ExerciseList(exercises:
                ["Squats": Exercise(description: "Step 1: Place your feet shoulder-width apart. Keep your feet, shoulders, and hips facing forward. Step 2: Bend your knees and extend your buttocks backward as if you are going to sit back into a chair. Make sure that you keep your knees behind your toes and your weight in your heels. Step 3: Push through your heels and rise back up to your standing position. That’s 1 rep. Step 4: Do 10-15 reps of 2-3 sets. Bonus: You can also add weights via exercise balls or dumbbells to make this exercise harder. You can also add a jump after your squat for Jump Squats.", image: UIImage(named: "Squats")!),
                 "Single Leg Squat": Exercise(description: "Step 1: Stand on one foot with your other leg bent at the knee. Step 2: Hold both arms out in front of you during the exercise to help with your balance. Step 3: Once you’re balanced on one leg, squat down as low as you can without losing your form or toppling over. Don’t let your knee go past the front of your toes while you squat. Step 4: Pause at the bottom of the squat for a second, then push back up through your heel, squeezing your glutes as you go. That’s 1 rep. Step 5: Try for 5-10 reps for 2-3 sets. Bonus: Another version of this exercise if the Pistol Squat.", image: UIImage(named: "Single Leg Squat")!),
                 "Pistol Squat": Exercise(description: "Step 1: Stand on one leg with the other extended out straight in front of you and drop into a deep squat. Step 2: At the bottom of the movement the hamstring on your standing leg should be resting on your calf, with your other leg still stretched out ramrod straight, so you look like a pistol. Step 3: Push up using your bottom foot into your starting position. That’s 1 rep. You may need to push off the ground slightly when you first begin doing this exercise. Step 4:Try for 3-5 reps for 2-3 sets.", image: UIImage(named: "Pistol Squat")!),
                 "Step-Ups": Exercise(description: "Step 1: Start standing facing a sturdy box or surface about a foot tall. Step 2: Step your left foot straight up onto the box. Step 3: Shift your weight into your left foot and pick your right foot up off the floor, drive the knee toward the chest, and come to balance on your left leg. Step 4: Keep core engaged, and slowly reverse the movement to return to the starting position. That's one rep. Step 5: Do 10-12 reps for 2-3 sets on each side.", image: UIImage(named: "Step Ups")!),
                 "Bulgurian Split Squat": Exercise(description: "Step 1: Start standing tall with your right foot forward and the left back (as if standing on railroad tracks), top of left foot resting on a box and hands on hips. Step 2: Shift weight into the front right foot, engage your core, keep your torso upright, and bend at both knees to lower your body until your back knee hovers just above the floor or gently taps down. Step 3: Press through your right foot to straighten your legs and return to the starting position. That's one rep. Step 4: Do 10-12 reps for 2-3 sets on each side.", image: UIImage(named: "Bulgarian Split Squat")!),
                 "Goblet Squat": Exercise(description: "Step 1: Grab a kettlebell or dumbbell. Step 2: Hold the kettlebell or the top head of the dumbbell at chest height with your elbows bent and close to the ribs. Step 3: Stand with your feet shoulder-width apart and toes slightly turned out. Step 4: Engage your core and push your hips back as if lowering into a chair. Keep the chest upright and spine straight; push knees outward and distribute weight evenly through feet. Step 5: When your thighs are parallel with the floor, press through your feet to reverse the movement and return to the starting position. That's one rep. Step 6: Do 1-12 reps for 2-3 sets.", image: UIImage(named: "Goblet Squat")!),
                 "Curtsy Lunge": Exercise(description: "Step 1: Start standing tall with feet under hips. Engage your core, lift your right foot off the floor and take a big step back and to the outside of your left foot. Step 2: Bend at knees until your right knee taps the floor behind your left foot. Step 3: Drive through feet to reverse the movement and return to the starting position. That's one rep. Step 4: Do 10-12 reps on each side for 2-3 sets.", image: UIImage(named: "Curtsy Lunge")!),
                 "Tempo Squat": Exercise(description: "Step 1: Start standing with feet parallel and shoulder-width apart, arms at sides. Step 2: Engage your core, push your hips back, and bring your arms forward to clasp at chest height. Step 3: Begin to lower down slowly to the count of five, stopping when your thighs are parallel with the floor. Step 4: Press through feet to reverse the movement in one count and return to start. That's one rep. Step 5: Do 10-12 reps for 2-3 sets.", image: UIImage(named: "Tempo Squat")!)
            ]),
            "Calves": ExerciseList(exercises:
                ["Calf Raises": Exercise(description: "This exercise does not require any equipment. Step 1: Stand with your hands on your hips with your feet together. Step 2: Raise onto your toes and lower back down onto your heels. That’s 1 rep. Step 3: Try for 10-15 for 2-3 sets. Bonus: To make this exercise harder, try holding dumbbells while you do this exercise. Or you could try doing one leg at a time.", image: UIImage(named: "Calf Raises")!),
                 "Seated Calf Raises": Exercise(description: "Step 1: Grab a pair of dumbbells. Step 2: Sit on a bench and rest the balls of your feet on a block or step. Step 3: Hold dumbbells on your thighs. Your knees should be bent 90 degrees and your toes pointing straight ahead. Step 4: Allow your heels to drift toward the floor until you feel a stretch in your calves. Step 5: Drive the balls of your feet into the platform and raise your heels as high as possible. That’s 1 rep. Step 6: Try for 10 reps for 2-3 sets.", image: UIImage(named: "Seated Calf Raises")!),
                 "Jump Rope": Exercise(description: "Step 1: Grab a jump rope. Step 2: Holding the handles of a jump rope in each hand, jump with both feet as you spin the rope under you and over your head. Keep your core engaged and your shoulders lowered. Try not to let your heels hit the floor, stay on your toes while you jump and land. Step 3: Jump rope for about 1 minute for 3 sets. Take short breaks in between each set. Bonus: You can increase the difficulty by swinging the rope twice under your feet before you land for each jump, or jump on one leg instead of two.", image: UIImage(named: "Jump Rope")!),
                 "Farmer's Walk": Exercise(description: "Step 1: Grab a pair of dumbbells. Step 2: Hold a dumbbell in each hand with your feet hip-width apart. Step 3: Keeping your shoulders down and your core engaged, lift your heels so you’re standing on your toes. Step 4: Without letting your heels touch the ground, walk forward on your toes for 30 seconds to 1 minute. That’s 1 rep. Try doing 3 reps with short breaks between each set.", image: UIImage(named: "Farmers Walk")!),
                 "Tiptoe Walk": Exercise(description: "This exercise does not require any equipment. Step 1: Raise onto your toes. Step 2: Walk around without letting your heels touch the ground. Step 3: Do this for 1-2 minutes for 2-3 sets with short breaks between each set.", image: UIImage(named: "Tiptoe Walk")!),
                 "Jump Squat": Exercise(description: "Step 1: Grab a single dumbbell or medicine ball. Step 2: Holding the dumbbell one side in each hand, stand tall with your feet shoulder-width apart. Step 3: Push your hips back to lower down until your thighs are parallel with the ground and you’re in squat position. Step 4: In one explosive movement, straighten your legs to come out of the squat position and jump off the ground. Step 5: Land softly with bent knees as you lower back into the squat position. That’s 1 rep. Step 6: Try for 10 reps for 2-3 sets. ", image: UIImage(named: "Jump Squat")!),
                 "Jumping Jacks": Exercise(description: "This exercise does not require any equipment. Step 1: Stand with your feet together and arms at your sides. Step 2: Jump and spread your legs outside shoulder width as you clap your hands overhead. Step 3: Jump and return your hands and feet to the starting position. That’s 1 rep. Step 4: Do 10-20 reps for 2-3 sets.", image: UIImage(named: "Jumping Jacks")!),
                 "Agility Ladder": Exercise(description: "Step 1: Grab an agility ladder and lay it out on the floor. If you don’t have an agility ladder, creating lines with tape or chalk on the floor is a great alternative. Step 2: Stand at one end of the ladder. Step 3: Run or hop from one end of the agility ladder to the other. That’s one rep. Step 4: Go through the ladder for 30 seconds to 1 minute for 2-3 sets with small breaks between each set.", image: UIImage(named: "Agility Ladder")!)
            ])
        ]
            
      

        // Uncomment the following line to preserve selection between presentations
        // self.clearsSelectionOnViewWillAppear = false

        // Uncomment the following line to display an Edit button in the navigation bar for this view controller.
        // self.navigationItem.rightBarButtonItem = self.editButtonItem
    }

    // MARK: - Table view data source

    override func numberOfSections(in tableView: UITableView) -> Int {
        // #warning Incomplete implementation, return the number of sections
        return 1
    }
//Ths following lines on code provides the number of cells based on the number of Target Areas - for example: Triceps and Biceps

    override func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        // #warning Incomplete implementation, return the number of rows
        return workouts.keys.count
    }

    
    override func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: "workouts", for: indexPath)
        
// The follwing lines of code sets up the target areas as the titles for each cell in the table view
        
        let bodyParts = Array(workouts.keys)
        cell.textLabel?.text = bodyParts[indexPath.row]
        
        // Configure the cell...

        return cell
    }
    

    /*
    // Override to support conditional editing of the table view.
    override func tableView(_ tableView: UITableView, canEditRowAt indexPath: IndexPath) -> Bool {
        // Return false if you do not want the specified item to be editable.
        return true
    }
    */

    /*
    // Override to support editing the table view.
    override func tableView(_ tableView: UITableView, commit editingStyle: UITableViewCell.EditingStyle, forRowAt indexPath: IndexPath) {
        if editingStyle == .delete {
            // Delete the row from the data source
            tableView.deleteRows(at: [indexPath], with: .fade)
        } else if editingStyle == .insert {
            // Create a new instance of the appropriate class, insert it into the array, and add a new row to the table view
        }    
    }
    */

    /*
    // Override to support rearranging the table view.
    override func tableView(_ tableView: UITableView, moveRowAt fromIndexPath: IndexPath, to: IndexPath) {

    }
    */

    /*
    // Override to support conditional rearranging of the table view.
    override func tableView(_ tableView: UITableView, canMoveRowAt indexPath: IndexPath) -> Bool {
        // Return false if you do not want the item to be re-orderable.
        return true
    }
    */

    
    // MARK: - Navigation

    // In a storyboard-based application, you will often want to do a little preparation before navigation
    
// The follwing lines of code sets up passing the list of exercises available based on the user's selected target area for working out onto the ExerciseTableViewController
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        // Get the new view controller using segue.destination.
        // Pass the selected object to the new view controller.
        let bodyParts = Array(workouts.keys)
        if segue.identifier == "exercises" {
            if let exerciseViewController = segue.destination as? ExerciseTableViewController,
            let cell = sender as? UITableViewCell,
            let indexPath = self.tableView.indexPath(for: cell),
            let exercise = workouts[bodyParts[indexPath.row]] {
                exerciseViewController.exerciseList = exercise
            
        }
    }
    

}
}
